algoritmo "semnome"
// Função :
// Autor :
// Data : 27/09/2016
// Seção de Declarações 
var
   VetA : vetor[1..5]de inteiro
   Cont , Soma: inteiro
inicio
// Seção de Comandos 
para cont de 1 ate 5 passo 1 faca
escreva("Informe um numero inteiro: ")
Leia(VetA [Cont])
se vetA[Cont] mod 2 = 1 entao
Soma:=Soma + VetA[Cont]
Fimse
Fimpara
Escreval("a soma de todos os numeros impares informados e:",soma)
fimalgoritmo
