algoritmo "semnome"
// Função :
// Autor :
// Data : 27/09/2016
// Seção de Declarações 
var
   VetA, vetB: vetor [1..8] de real
   Cont:Inteiro
inicio
// Seção de Comandos 
para cont de 1 ate 8 passo 1 faca
escreval("informe um numero: ")
LEIA(VETa[cONT])
VETb[cONT] :=vETa[cONT] * 3
FIMPARA
ESCREVAL
PARA CONT DE 1 ATE 8 PASSO 1 FACA
ESCREVAL(vETa[cONT],"x 3 =",vETb[cONT])
FIMPARA
fimalgoritmo
