algoritmo "semnome"
// Função :
// Autor :
// Data : 14/07/2016
// Seção de Declarações 
var
n1,n2,n3,n4,Media : real
inicio
// Seção de Comandos
escreva ("Diga a nota 1:")
leia(n1)
escreva ("Diga a nota 2:")
leia(n2)
escreva("Diga a nota 3:")
leia(n3)
escreva("Diga a nota 4:")
leia(n4)
Media<-n1+n2+n3+n4/4
se(Media>=5)entao
escreva("Você foi aprovado:")
senao
escreva("Você foi reprovado:")
fimse
fimalgoritmo
