algoritmo "questão 12"
// Função :
// Autor : isis reis, coringa e will
// Data : 15/09/2016
// Seção de Declarações 
var
 a, b : inteiro
inicio
// Seção de Comandos 

para a de 1 ate 10 passo 1 faca
     para b de 1 ate 10 passo 1 faca
     
     se ( a >= b ) entao
        escreva ( "x - x " )
     senao
          escreva ( a, " -", b )
     fimse
     
     fimpara
     
     escreval ()
fimpara
fimalgoritmo
