algoritmo "semnome"
// Função :
// Autor :
// Data : 08/09/2016
// Seção de Declarações
//Desenvolver um programa que apresente o total da soma de n números inteiros
//do número 1 até n, onde n é um valor informado pelo usuário.
var
n,r,x,t: inteiro
inicio
// Seção de Comandos
Escreval("Diga um numero")
Leia(n)
Para r de 1 ate n passo 1 faca
x<-x+r
Fimpara
Escreval (x)
Fimalgoritmo
