algoritmo "Lista 6 ex 8"
// Autor :Matheus Teixeira e Isis Reis
// Data : 08/09/2016
// Seção de Declarações 
var
nome,sexo:caracter
x,idade:inteiro
inicio
Para x de 1 ate 20 passo 1 faca
Escreva("Diga seu nome:")
leia(nome)
Escreva("Diga seu sexo:")
leia(sexo)
Escreva("Diga sua idade:")
leia(idade)
Se ((idade>21) e (sexo="Masculino"))entao
Escreva("Seus dados são:", nome , sexo, idade )
senao
Escreva("Seus dados não podem ser exibidos:")
fimse
fimpara
fimalgoritmo

